# GitHub Action for generating a contribution graph with a snake eating your contributions.
name: Generate Snake

# Controls when the action will run. This action runs every month.
on:
  # This command allows us to run the Action automatically from the Actions tab.
  workflow_dispatch:
  schedule:
      # every month
    - cron: "0 0 1 * *"

# The sequence of runs in this workflow:
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    timeout-minutes: 10

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@master  
      - uses: Platane/snk@master
        with:
          github_user_name: sgiraz
          svg_out_path: | 
            assets/github-contribution-grid-snake.svg
            assets/github-snake-dark.svg?palette=github-dark
          
      - name: Update Repo
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git config --global push.default upstream
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
          git commit -am "github-user-contribution updated"
          git push
